#!/bin/bash



# ********************************************************************
#
#   Command Section
#
# ********************************************************************





# ********************************************************************
#
#       Configuration Section
#
# ********************************************************************

PYTHON=/usr/local/bin/python2.7


BASE_DIR=/netsim
BIN_DIR=${BASE_DIR}/bin
ETC_DIR=${BASE_DIR}/etc
INST_DIR=${BASE_DIR}/inst
LIB_DIR=${BASE_DIR}/lib





show_fn()
{
	_show_fn_arg_=$@
	$PYTHON ${BIN_DIR}/show.py $_show_fn_arg_
}
open_fn()
{
	_open_fn_arg_=$1
	$PYTHON ${BIN_DIR}/open.py $_open_fn_arg_

}
select_fn()
{
	_select_fn_arg_=$1
        $PYTHON ${BIN_DIR}/select_1.py $_select_fn_arg_
}
dump_mo_tree_fn()
{
	_cmd_run_=$@
	echo $_cmd_run_
	$PYTHON ${BIN_DIR}/dump_mo_tree.py $_cmd_run_
}

exit_fn()
{
	break
}



get_cmd_arg()
{
	_usr_input_=$1
	w=`echo $i | wc -w`
        if [ $w -gt 1 ];then
                cmd=`echo $i | cut -d" " -f1`
                arg=`echo $i | cut -d" " -f2-`
        else
                cmd=$i
        fi

}
while read i; do

	get_cmd_arg $i

	case $cmd in
	        .show ) show_fn $arg;;
		.open ) open_fn $arg;;
		.select ) select_fn $arg;;
		dumpmotree*) dump_mo_tree_fn $i;;
		.exit ) exit_fn;;
		* ) echo "Please answer show or open.";;
	esac
done

